[TITLE:How great is our god]

[ORDER:Intro,Str 1,Ref,Str 2,Ref, Bridge, Ref, Ref]

[block: Intro]
[G] [Em7] [C] [D] [G]

[BLOCK: Str 1]
The *[G]sple<r>ndor* of <b>the Kin<r>g, [Em7]clo**thed in<r> ma**jesty
Let all the earth re[C]joice, All the earth re[D]joice | so sehen | annotationen aus
He [G]wraps himself in Light, and [Em7]darkness tries to hide
And trembles at His [C]voice, Trembles at His [D]voice

[BLOCK: Ref]
How [G]great is our God, sing with me       | test1     ;   test2; test3; test4; test5 | always
How [Em7]great is our God, and all will see
How [Cmaj7]great, how [D]great is our [G]God

[BLOCK: Str 2]
[G]Age to age He stands, and [Em7]time is in His hands
Beginning and the [C]end, Beginning and the [D]end
The [G]Godhead Three in One, [Em7]Father Spirit Son
The [C]Lion and the Lamb, The [D]Lion and the Lamb

[bLoCk: Bridge]
[G]Name above all names, [Em7]Worthy of our praise
My [Cmaj7]heart will sing, How [D]great is our [G]God


